baseURL: https://blog.reywilliams.com/
languageCode: en-us
title: ReysCorner

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home: [HTML, RSS, JSON]

params:
  description: "A dev's little corner of the internet"
  author: Rey Williams
  personalSite: https://reywilliams.com/
  socialImage: images/wide-angle-flat-mono.png
  terrainImage: images/terrain.svg
  themeColor: "#0a0a0a"
  dateFormat: January 2, 2006
  listDateFormat: Jan 02, 2006

menu:
  main:
    - name: Writing
      url: /
      weight: 10
    - name: Archive
      pageRef: /archive
      weight: 20
    - name: Tags
      pageRef: /tags
      weight: 30
    - name: Search
      pageRef: /search
      weight: 40
  footer:
    - name: About
      pageRef: /whoami
      weight: 10
    - name: RSS
      url: index.xml
      weight: 20
    - name: GitHub
      url: https://github.com/reywilliams
      weight: 30

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

caches:
  images:
    dir: :cacheDir/images
